defaults: &defaults
  adapter: mysql2
  database: redmine
  host: 127.0.0.1
  username: root
  password: root
  encoding: utf8

development:
  <<: *defaults
  database: redmine_development

test:
  <<: *defaults
  database: redmine_test

production:
  <<: *defaults
